# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-30 18:02
from __future__ import unicode_literals

import core.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorPlatformJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', core.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Author')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Platform')),
            ],
        ),
        migrations.CreateModel(
            name='BookPlatformJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64)),
                ('rating', models.FloatField(default=None, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=None)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', core.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Book')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Platform')),
            ],
        ),
        migrations.RemoveField(
            model_name='editionplatformjoin',
            name='url',
        ),
        migrations.AddField(
            model_name='editionplatformjoin',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='editions',
            field=models.ManyToManyField(related_name='users', through='core.EditionUserJoin', to='core.Edition'),
        ),
        migrations.AlterField(
            model_name='editionplatformjoin',
            name='rating',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bookplatformjoin',
            unique_together=set([('book', 'platform')]),
        ),
        migrations.AlterUniqueTogether(
            name='authorplatformjoin',
            unique_together=set([('author', 'platform')]),
        ),
    ]
