# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='books',
            field=models.ManyToManyField(related_name='users', through='core.UserBookJoin', to='core.Book'),
        ),
    ]
