# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-13 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180713_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='num_edition',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
