# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-13 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180713_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='core.Language'),
        ),
    ]
