/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule GroupView_viewer.graphql
 * @generated SignedSource<<14eded873cef70ea8944da9c354104d7>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type GroupView_viewer = {|
  +group: ?{|
    +id: string;
    +name: string;
  |};
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [
    {
      "kind": "RootArgument",
      "name": "nameUrl",
      "type": "String"
    }
  ],
  "kind": "Fragment",
  "metadata": null,
  "name": "GroupView_viewer",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": null,
      "args": [
        {
          "kind": "Variable",
          "name": "nameUrl",
          "variableName": "nameUrl",
          "type": "String"
        }
      ],
      "concreteType": "Group",
      "name": "group",
      "plural": false,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "id",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "name",
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "Viewer"
};

module.exports = fragment;
