# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(through='backend.UserBookJoin', to='backend.Book'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set([('name', 'author')]),
        ),
    ]
