# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170902_0057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbookjoin',
            unique_together=set([('user', 'book')]),
        ),
    ]
