# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20170902_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookjoin',
            name='rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
