# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-02 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_userbookjoin_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publishing_year',
            field=models.IntegerField(null=True),
        ),
    ]
