/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule core_GroupView_Query.graphql
 * @generated SignedSource<<af80edfcd0c3ba0377b142483411c142>>
 * @relayHash 85f33c8902b8052324bd5c9ce66df094
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/


/*
query core_GroupView_Query(
  $nameUrl: String!
) {
  viewer {
    ...GroupView_viewer
    id
  }
}

fragment GroupView_viewer on Viewer {
  group(nameUrl: $nameUrl) {
    id
    name
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "nameUrl",
        "type": "String!",
        "defaultValue": null
      }
    ],
    "kind": "Fragment",
    "metadata": null,
    "name": "core_GroupView_Query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": "viewer",
        "args": null,
        "concreteType": "Viewer",
        "name": "__viewer_viewer",
        "plural": false,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "GroupView_viewer",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "core_GroupView_Query",
  "query": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "nameUrl",
        "type": "String!",
        "defaultValue": null
      }
    ],
    "kind": "Root",
    "name": "core_GroupView_Query",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Viewer",
        "name": "viewer",
        "plural": false,
        "selections": [
          {
            "kind": "LinkedField",
            "alias": null,
            "args": [
              {
                "kind": "Variable",
                "name": "nameUrl",
                "variableName": "nameUrl",
                "type": "String"
              }
            ],
            "concreteType": "Group",
            "name": "group",
            "plural": false,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "id",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "name",
                "storageKey": null
              }
            ],
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          }
        ],
        "storageKey": null
      },
      {
        "kind": "LinkedHandle",
        "alias": null,
        "args": null,
        "handle": "viewer",
        "name": "viewer",
        "key": "",
        "filters": null
      }
    ]
  },
  "text": "query core_GroupView_Query(\n  $nameUrl: String!\n) {\n  viewer {\n    ...GroupView_viewer\n    id\n  }\n}\n\nfragment GroupView_viewer on Viewer {\n  group(nameUrl: $nameUrl) {\n    id\n    name\n  }\n}\n"
};

module.exports = batch;
