/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Page_viewer.graphql
 * @generated SignedSource<<ba833ce8e87f61bceacfe0bd67e9592b>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Page_viewer = {| |};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Page_viewer",
  "selections": [
    {
      "kind": "FragmentSpread",
      "name": "Header_viewer",
      "args": null
    }
  ],
  "type": "Viewer"
};

module.exports = fragment;
