/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule MyBookList_books.graphql
 * @generated SignedSource<<254ce22748d28298159201f12b53cb17>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type MyBookList_books = {|
  +id: string;
  +name: string;
  +author: string;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": {
    "plural": true
  },
  "name": "MyBookList_books",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "name",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "author",
      "storageKey": null
    }
  ],
  "type": "Book"
};

module.exports = fragment;
