/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule MyBookList_bookshelf.graphql
 * @generated SignedSource<<d90738fd5e9bb4104637f371f9a1c7b5>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type MyBookList_bookshelf = {|
  +id: string;
  +book: {|
    +title: string;
    +author: string;
  |};
  +rating: ?number;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": {
    "plural": true
  },
  "name": "MyBookList_bookshelf",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "Book",
      "name": "book",
      "plural": false,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "title",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "author",
          "storageKey": null
        }
      ],
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "rating",
      "storageKey": null
    }
  ],
  "type": "BookshelfEntry"
};

module.exports = fragment;
