/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule rootViewerQuery.graphql
 * @generated SignedSource<<871158ab0e9cabe1a57b607aa86f07b0>>
 * @relayHash 9c4012052d1aa22aa7c670116fc36833
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/


/*
query rootViewerQuery {
  viewer {
    ...Account_viewer
    ...Landing_viewer
    id
  }
}

fragment Account_viewer on Viewer {
  id
}

fragment Landing_viewer on Viewer {
  id
  user {
    email
    username
    id
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "rootViewerQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": "viewer",
        "args": null,
        "concreteType": "Viewer",
        "name": "__viewer_viewer",
        "plural": false,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "Account_viewer",
            "args": null
          },
          {
            "kind": "FragmentSpread",
            "name": "Landing_viewer",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "rootViewerQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "rootViewerQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Viewer",
        "name": "viewer",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "UserNode",
            "name": "user",
            "plural": false,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "email",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "username",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "id",
                "storageKey": null
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": null
      },
      {
        "kind": "LinkedHandle",
        "alias": null,
        "args": null,
        "handle": "viewer",
        "name": "viewer",
        "key": "",
        "filters": null
      }
    ]
  },
  "text": "query rootViewerQuery {\n  viewer {\n    ...Account_viewer\n    ...Landing_viewer\n    id\n  }\n}\n\nfragment Account_viewer on Viewer {\n  id\n}\n\nfragment Landing_viewer on Viewer {\n  id\n  user {\n    email\n    username\n    id\n  }\n}\n"
};

module.exports = batch;
